name: Build, Publish, and Release

on:
  workflow_dispatch:

jobs:
  build_publish_release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      # Extract version from pom.xml
      - name: Get the version
        run: echo "PROJECT_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV

      # Build the code
      - name: Build with Maven
        run: mvn clean install

      # Publish to GitHub Package Repository
      - name: Publish to GitHub Package Repository
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      # Tag the new version
      - name: Create Tag
        run: git tag ${{ env.PROJECT_VERSION }}

      # Push the new tag
      - name: Push Tag
        run: git push origin ${{ env.PROJECT_VERSION }}

      # Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          release_name: Release ${{ env.PROJECT_VERSION }}
          body_path: CHANGELOG.md  # Use your changelog file as the body
          draft: false
          prerelease: false
